#ifndef HAL_HEART_RATE_HEART_RATE_CFG_H_
#define HAL_HEART_RATE_HEART_RATE_CFG_H_

#define HHEART_RATE_BASELINE_WINDOW       64U
#define HHEART_RATE_REFRACTORY_MS         300U
#define HHEART_RATE_HISTORY_LEN           6U
#define HHEART_RATE_SAMPLE_PERIOD_MS      10U
#define HHEART_RATE_LPF_ALPHA_NUM         3U
#define HHEART_RATE_LPF_ALPHA_DEN         10U
#define HHEART_RATE_MIN_VALID_BPM         30U
#define HHEART_RATE_MAX_VALID_BPM         220U
#define HHEART_RATE_MIN_SIGNAL_AMPLITUDE  120
#define HHEART_RATE_MIN_VALID_BEATS       3U
#define HHEART_RATE_STABLE_SAMPLES        100U
#define HHEART_RATE_OUTLIER_RESET_COUNT   5U
#define HHEART_RATE_OUTLIER_RATIO_NUM     2U
#define HHEART_RATE_OUTLIER_RATIO_DEN     5U

#endif /* HAL_HEART_RATE_HEART_RATE_CFG_H_ */